select * from customer limit 20

--total revenue generated by male vs female?
select gender,sum(purchase_amount) as revenue from customer group by gender

--customer used discount but spent more than avg?

select customer_id,purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount)from customer)

-- top 5 products with highest average review rating
select item_purchased,avg(review_rating) from customer as average_product_rating 
group by item_purchased order by avg(review_rating) desc limit 5

--compare avg purchase amounts b/w standard and express shipping
select shipping_type ,round(avg(purchase_amount),3) from customer where shipping_type in ('Standard','Express')  group by shipping_type

--avg spend and total revenue b/w subscribers and non subscribers

select subscription_status , count(customer_id) as total_customers ,
round(avg(purchase_amount),3) as avg_spend, 
sum(purchase_amount) as total_revenue from customer group by subscription_status

--5 products with highest percentage of purchases with discount applied

select item_purchased, round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2)  
as discount_rate from customer group by item_purchased order by discount_rate desc limit 5

--segment customers into new,returning,loyality based on previous purchase 
--and count persons in each segment

with customer_type as (
select customer_id,previous_purchases,
case
      when previous_purchases =1 then 'NEW'
      when previous_purchases between 2 and 10 then 'RETURNING'
      else 'LOYAL'
      end as customer_segment 
from customer)
select customer_segment,count(*) as total_customers
from customer_type group by customer_segment

-- top 3 products in each category
with item_counts as(
select item_purchased,category ,count(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION by category order by count(customer_id) desc) as item_rank
from customer group  by category,item_purchased) 

select item_rank,item_purchased,category,total_orders from item_counts where item_rank <=3;



-- customers who are repeat buyers(more than 5 ) are likely to subscribe 
select subscription_status,count(customer_id) as repeated_customers from customer
where previous_purchases > 5 group by subscription_status

-- revenue by each age group 

select age_group,sum(purchase_amount)  as revenue from customer group by age_group order by revenue desc